spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/data/sample/${spring.application.name}/db;
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
